export const layout_header = `<header class="fixed top-0 left-0 w-full z-50 bg-white/90 backdrop-blur-md border-b border-transparent transition-all duration-300" id="header">
<div class="container max-w-7xl mx-auto px-4 md:px-8 position-relative d-flex align-items-center justify-content-between"><a href="/" class="logo d-flex align-items-center me-auto"><div class="flex items-center select-none h-20"><img alt="VALO Connective Solutions Logo" class="h-full w-auto object-contain" src="https://www.thevalo.net/logo.svg?v=4"></div></a><nav id="navmenu" class="navmenu">
<div class="mobile-nav-extras hidden">
  <div class="absolute top-[20px] left-[20px] z-[9999] d-xl-none"><a href="/" class="!border-none !p-0"><img alt="VALO Logo" class="h-12 w-auto object-contain" src="https://www.thevalo.net/logo.svg?v=4"></a></div>
  <div class="w-full px-6 pt-[90px] d-xl-none mb-6"><a href="/contact" class="btn-getstarted !m-0 !w-full !block text-center !py-3.5 !rounded-2xl !text-[17px] !font-semibold !text-white shadow-sm active:scale-[0.98] transition-transform bg-[#1868DB] hover:bg-[#1868DB]">Contact Us</a></div>
</div>
<ul class="d-flex align-items-center d-none d-xl-flex"><li><a href="/" class="active">Home</a></li><li><a href="/about" class="">About</a></li><li><a href="/services" class="">Services</a></li><li><a href="/staff-augmentation" class="">Staff Augmentation</a></li><li><a href="/security" class="">Security</a></li><li><a href="/case-studies" class="">Case Studies</a></li></ul><i class="mobile-nav-toggle d-xl-none bi bi-three-dots-vertical text-2xl"></i></nav><a class="btn-getstarted d-none d-xl-block" href="/contact">Contact Us</a></div>
</header>`;

export const layout_footer = `<footer  id="footer" class="footer mt-12 bg-white text-[#101214] pb-4">
<div class="container max-w-7xl mx-auto px-4 md:px-8"><div class="bg-[#f4f5f7] rounded-3xl px-8 py-12 md:px-16 md:py-16"><div class="row gy-5"><div class="col-lg-4 col-md-6 d-flex flex-column gap-3"><a href="/" class="d-flex align-items-center text-decoration-none mb-3"><img class="h-6 object-contain" alt="Valo Icon" src="https://www.thevalo.net/logo-icon.svg?v=3"></a><ul class="list-unstyled d-flex flex-column gap-3 mb-0 text-[13px] font-bold"><li><a href="/" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">Home</a></li><li><a href="/about" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">About Us</a></li><li><a href="/case-studies" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">Case Studies</a></li><li><a href="mailto:info@thevalo.net" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">Contact us</a></li></ul></div><div class="col-lg-4 col-md-6 d-flex flex-column gap-3"><h4 class="font-extrabold text-[#101214] mb-2 text-[11px] tracking-widest uppercase">Core Services</h4><ul class="list-unstyled d-flex flex-column gap-3 mb-0 text-[13px] font-medium text-[#101214]/80"><li>Custom Software Engineering</li><li>Precision UI/UX Design</li><li><a href="/staff-augmentation" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">IT Staff Augmentation</a></li><li>Cloud &amp; DevOps Architecture</li><li>AI &amp; Data Solutions</li><li><a href="/security" class="text-[#101214] hover:text-[#1868DB] text-decoration-none">Security &amp; Compliance</a></li></ul></div><div class="col-lg-4 col-md-6 d-flex flex-column gap-3"><h4 class="font-extrabold text-[#101214] mb-2 text-[11px] tracking-widest uppercase">Office</h4><ul class="list-unstyled d-flex flex-column gap-3 mb-0 text-[13px] font-medium text-[#101214]"><li>Office 01, Ground Floor</li><li>Plaza No 6, Street 8</li><li>Sector J, DHA-II</li><li>Islamabad</li><li class="mt-3"><a href="mailto:info@thevalo.net" class="text-[#101214] font-bold hover:text-[#1868DB] text-decoration-none">info@thevalo.net →</a></li></ul></div></div></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-center py-4 text-[12px] text-[#4a5568] font-medium px-4"><div>Copyright © 2026 VALO</div><div class="d-flex gap-4 mt-3 mt-md-0 align-items-center"><a href="/privacy" class="text-[#4a5568] hover:text-[#1868DB] text-decoration-none">Privacy Policy</a><a href="/terms" class="text-[#4a5568] hover:text-[#1868DB] text-decoration-none">Terms &amp; Conditions</a><a href="/faqs" class="text-[#4a5568] hover:text-[#1868DB] text-decoration-none">FAQs</a></div></div></div>
</footer>`;

